
name: Build and deploy Node.js app to Azure Web App 


on:
  push:
    #paths-ignore:
    #  - 'server/**'   # Only trigger the deployment if the client folder changed, soo ignore the server folder changes
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build 

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
